/*
 * agenda.java
 *
 * Created on 10 de febrero de 2008, 12:46
 */

package agenda;
import java.awt.*;
import java.awt.geom.*;
import java.awt.image.*;
import javax.swing.*;
import java.awt.event.*;
import java.awt.Graphics;
import java.awt.Toolkit;
import java.awt.Image;
/**
 *
 * @author  sheila
 */
public class agenda extends javax.swing.JFrame {
    //creo todos los paneles
    
    /** Creates new form agenda */
    public agenda() {
        initComponents();
        this.setBounds(80,70,850,650);
       
         //pongo el fondo de la ventana
        //fondo fon = new fondo();
        //inicializo los paneles
        panel_menu pmenu=new panel_menu();
        entrada entra=new entrada(pmenu);
        
       // agrego los paneles
        //getContentPane().add(entra);
         getContentPane().add(entra, new org.netbeans.lib.awtextra.AbsoluteLayout());
         getContentPane().add(pmenu, new org.netbeans.lib.awtextra.AbsoluteLayout());
         pmenu.setVisible(false);
        System.out.println("entra");
       // getContentPane().add(fon);
     // this.pack();
      

    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Código Generado  ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agenda().setVisible(true);
            }
        });
        
    }
    
    // Declaración de varibales -no modificar//GEN-BEGIN:variables
    // Fin de declaración de variables//GEN-END:variables
/*  private void ocultar_paneles(){
       // panel_nueva_hora.setVisible(false);
       
    }   
}
class fondo extends JPanel {
    Color naranja = new Color(225, 102, 0);
    Color gris = new Color(238, 238, 238);
    
    public fondo(){
        this.setSize(1024, 768);
    }
    
    public void paint(Graphics g){
        Graphics2D g2d = (Graphics2D) g;  // convertir g a Graphics2D
        //super.paint(g);
        //dibujo el fondo
        g2d.setColor(gris);
        g2d.fillRect(0, 0, this.getWidth(), this.getHeight());
        //dibujo los bordes
        g2d.setColor(naranja);
        g2d.setStroke(new BasicStroke(5));
        g2d.draw(new Rectangle2D.Double(5, 31, this.getWidth() - 8, this.getHeight() - 34));
        g2d.fillRect(8, 28, 750, 55);
        g2d.fillOval(680, -37, 145, 120);
        g2d.fillRect(191, this.getHeight() - 60, this.getWidth() - 190, 55);
        g2d.fillOval(115, this.getHeight() - 60, 145, 120);
        Font f = new Font("Times New Roman", Font.BOLD, 40);
        g2d.setFont(f);
        g2d.setColor(Color.WHITE);
        g2d.drawString("Gestión de Protección Civil", 50, 69);
        Font f1 = new Font("Times New Roman", Font.BOLD, 35);
        g2d.setFont(f1);
        g2d.drawString("Ayuntamiento de Villaquilambre", 160, this.getHeight() - 20);
        //dibujo el menú
        g2d.setColor(naranja);
        g.fillRoundRect(30, 150, 220, 500, 50, 50);
        g2d.setColor(Color.BLACK);
        g.drawRoundRect(30, 150, 220, 500, 50, 50);
            //dibujo las opciones principales del menú
        Font f2 = new Font("Times New Roman", Font.BOLD, 20);
        g2d.setFont(f2);
        g2d.setColor(gris);
        g2d.drawString("MENÚ", 105, 175);
        g2d.setStroke(new BasicStroke(2));
        g2d.drawLine(105, 180, 162, 180);
        //dibujo la zona central
        g2d.setStroke(new BasicStroke(5));
        g2d.setColor(Color.BLACK);
        g2d.drawRoundRect(280, 100, 710, 590, 50, 50);
        g2d.drawLine(280, 140, 990, 140);
    }}*/
}
