/*
 * panel_buscar_listado.java
 *
 * Created on 13 de febrero de 2008, 13:06
 */

package agenda;
import java.io.*;
import java.sql.*;
 import javax.swing.*;
 import java.awt.*;
 
import javax.swing.JTable;


/**
 *
 * @author  sheila
 */
public class panel_buscar_listado extends javax.swing.JPanel {
    Connection conexion;
       int i=0;
    Statement stmt;
    /** Creates new form panel_buscar_listado */
    public panel_buscar_listado() {
        initComponents();
       
        this.setBounds(0,100,700,300);
        JButton b=new JButton( "Copiar >>>" );
        
        this.getContentPane().add(b);
        /*try{
             conectar();
            stmt=conexion.createStatement();
            ResultSet rs=stmt.executeQuery("select * from datos where nombre=like '"+jTextField1.getText()+"%'");
            while (rs.next()) {
		String s = rs.getString("COF_NAME");
		Float n = rs.getFloat("PRICE");
		System.out.println(s + "   " + n);
                i=i+i;
                    }

         }catch (SQLException sql){}*/
    }
    public panel_buscar_listado(String nombre) {
        //System.out.println("primero"+nombre);
        int filas=0;
        //DefaultTableModel datos = new DefaultTableModel();
       
       /* datos.addColumn("NOMBRE");
        datos.addColumn("TELEFONO");
        datos.addColumn("DIRECCION");
        datos.addColumn("TELEFONO2");
        datos.addColumn("FAX");
        datos.addColumn("EMAIL");
        datos.addColumn("COMENTARIOS");*/
        
        
       
        this.add(new JButton( "Copiar >>>" ));
       System.out.println("llega aqui");
        try{
            //System.out.println("select count (nombre) AS resultado from datos where nombre=like '"+nombre+"%'");
             conectar();
             
            stmt=conexion.createStatement();
            
            ResultSet rs=stmt.executeQuery("select count(nombre) AS resultado from datos where nombre like '"+nombre+"%'");
           rs.next();
            filas=rs.getInt("resultado");
           // String[][]  re = new String[filas][7];*/
             ResultSet rs2=stmt.executeQuery("select * from datos where nombre like '"+nombre+"%'");
            String[] columnas={
            "NOMBRE",
            "TELEFONO",
            "TELEFONO2",
            "DIRECCION",
            "FAX",
            "EMAIL",
            "COMENTARIOS"
        };
        Object[][] re=new Object[filas][7];
        
           
      for(int i=0;i<filas;i++){
             while(rs2.next()){
                 re[i][0] =rs2.getString("nombre");
                 re[i][1] =rs2.getString("direccion");
                 re[i][2] =rs2.getString("telefono");
                 re[i][3] =rs2.getString("telefono2");
                 re[i][4] =rs2.getString("fax");
                 re[i][5] =rs2.getString("email");
                 re[i][6] =rs2.getString("comentarios");
             }
                }
            JTable tabla = new JTable(re,columnas);
            JScrollPane sx=new JScrollPane();
            this.add(sx);
            this.setVisible(true);

             
         

         }catch (SQLException sql){System.out.println("problema sql");}
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Código Generado  ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(102, 255, 102));
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 826, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    private void conectar(){
        try {

                Class.forName("com.mysql.jdbc.Driver");
                conexion = DriverManager.getConnection("jdbc:mysql://localhost/agenda?user=root&password=" );
                } catch( Exception e ) {

                System.out.println( "No se pudo cargar el driver JDBC: "+

                e.getLocalizedMessage() );

                return;

                }
    }
    
    // Declaración de varibales -no modificar//GEN-BEGIN:variables
    // Fin de declaración de variables//GEN-END:variables
    
}
