/*
 * panel_buscar.java
 *
 * Created on 11 de febrero de 2008, 21:45
 */

package agenda;

/**
 *
 * @author  sheila
 */
public class panel_buscar extends javax.swing.JPanel {
    panel_buscar1 pbuscar1;
    panel_buscar_listado plistado;
    /** Creates new form panel_buscar */
    public panel_buscar() {
        initComponents();
       pbuscar1=new panel_buscar1();
       plistado=new panel_buscar_listado();
       this.add(pbuscar1);
      // pbuscar1.setBounds(0,0
       this.add(plistado);
       //pbuscar1.setVisible(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Código Generado  ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 102));
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Declaración de varibales -no modificar//GEN-BEGIN:variables
    // Fin de declaración de variables//GEN-END:variables
    
}
