/*
 * panel_menu.java
 *
 * Created on 11 de febrero de 2008, 19:55
 */

package agenda;

/**
 *
 * @author  sheila
 */
public class panel_menu extends javax.swing.JPanel {
    
    /** Creates new form panel_menu */
    public panel_menu() {
        initComponents();
        this.setBounds(10,70,830,500);
        panel_insertar pinsertar=new panel_insertar();
        panel_buscar pbuscar=new panel_buscar();
        jTabbedPane1.addTab("INSERTAR",pinsertar);
        jTabbedPane1.addTab("BUSCAR",pbuscar);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Código Generado  ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jTabbedPane1 = new javax.swing.JTabbedPane();

        setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Declaración de varibales -no modificar//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    // Fin de declaración de variables//GEN-END:variables
    
}
